# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Pinnacle CRM
tagline:          'A Searchable Guide'
description:      'Searchable Guide for the Pinnacle Plus CRM'
#url:              https://github.com/nicolem/pplusguide
baseurl:
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Algolia'
  url:            https://www.algolia.com/
# Thanks to @mdo for the original theme
# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          10/6/17

github:
    repo:         https://github.com/nicolem/pplusgroup

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: '89GISEFJCF'
  index_name: 'name'
  read_only_api_key: 'eee16a3f674bba7cef27ecc6e14ac109'
  excluded_files:
    - 404.html
    - index.html
